# Generated by Django 4.1.7 on 2023-03-13 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="First_urls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=1000, unique=True)),
                ("title", models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name="Result_url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("child_link", models.CharField(max_length=1000, unique=True)),
                ("title", models.CharField(max_length=225)),
                ("number_of_link", models.IntegerField()),
                ("link_probability", models.FloatField(null=True)),
                (
                    "first_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pages.first_urls",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matrix_url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matrix", models.CharField(max_length=100000)),
                ("vector", models.CharField(max_length=100000)),
                (
                    "first_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pages.first_urls",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="List_of_urls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("child_link", models.CharField(max_length=1000)),
                (
                    "first_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pages.first_urls",
                    ),
                ),
                (
                    "main_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pages.result_url",
                    ),
                ),
            ],
        ),
    ]
