# Generated by Django 4.1.7 on 2023-03-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="first_urls",
            name="url",
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name="list_of_urls",
            name="child_link",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="list_of_urls",
            name="main_url",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="result_url",
            name="child_link",
            field=models.CharField(max_length=1000),
        ),
    ]
