# Generated by Django 4.1.7 on 2023-03-13 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Pages", "0002_remove_result_url_title"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Matrix_url",
        ),
    ]
